main = "src/lib/worker.ts"
compatibility_date = "2024-06-19"

[dev]
port = 8989
ip = "0.0.0.0"

# these migrations are append-only. you can't change them. if you do need to change something, do so
# by creating new migrations
[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["BemoDO"]

[[analytics_engine_datasets]]
binding = "MEASURE"

#################### Environment names ####################
# dev should never actually get deployed anywhere
[env.dev]
name = "dev-bemo-backend"

# we don't have a hard-coded name for preview. we instead have to generate it at build time and append it to this file.

# staging is the same as a preview on main:
[env.staging]
name = "main-bemo-backend"

# production gets the proper name
[env.production]
name = "bemo-backend"

#################### Durable objects ####################
# durable objects have the same configuration in all environments:
[[env.dev.durable_objects.bindings]]
name = "BEMO_DO"
class_name = "BemoDO"

[durable_objects]
bindings = [
  { name = "BEMO_DO", class_name = "BemoDO" },
]

[[env.preview.durable_objects.bindings]]
name = "BEMO_DO"
class_name = "BemoDO"

[[env.staging.durable_objects.bindings]]
name = "BEMO_DO"
class_name = "BemoDO"

[[env.production.durable_objects.bindings]]
name = "BEMO_DO"
class_name = "BemoDO"

#################### Analytics engine ####################
# durable objects have the same configuration in all environments:
[[env.dev.analytics_engine_datasets]]
binding = "MEASURE"

[[env.preview.analytics_engine_datasets]]
binding = "MEASURE"

[[env.staging.analytics_engine_datasets]]
binding = "MEASURE"

[[env.production.analytics_engine_datasets]]
binding = "MEASURE"

#################### Bemo R2 bucket ####################
# in dev, we write to the preview bucket and need a `preview_bucket_name`
[[env.dev.r2_buckets]]
binding = "DATA"
bucket_name = "bemo-data-preview"
preview_bucket_name = "bemo-data-preview"

# in preview and staging we write to the preview bucket
[[env.preview.r2_buckets]]
binding = "DATA"
bucket_name = "bemo-data-preview"

[[env.staging.r2_buckets]]
binding = "DATA"
bucket_name = "bemo-data-preview"

# in production, we write to the main bucket
[[env.production.r2_buckets]]
binding = "DATA"
bucket_name = "bemo-data"
